# Generated by Django 6.0.3 on 2026-03-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=255,
                null=True,
                verbose_name="Id сессии",
            ),
        ),
    ]
