# Generated by Django 6.0.3 on 2026-03-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на видео",
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
