# Generated by Django 6.0.3 on 2026-03-27 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_subscription_update"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="subscription_update",
            field=models.ManyToManyField(
                blank=True,
                help_text="Укажите обновление подписки",
                related_name="subscription_update",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обновление подписки",
            ),
        ),
    ]
