# Generated by Django 6.0.3 on 2026-03-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_course_subscription_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
