# Generated by Django 6.0.3 on 2026-03-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_course_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее обновление"
            ),
        ),
    ]
